version: '1.0'
services:
  - name: db
    type: postgres
    version: 9.6
    configuration: MasterSlave
    ports:
      - 5434
    env:
      POSTGRES_USER: "gandalf"
      POSTGRES_PASSWORD: null
    remoteAccess: false
    deployTo:
      - gandalf


  - name: platform
    type: docker
    image: bitwalker/alpine-elixir-phoenix
    version: latest
    ports:
      - 4000
      - 4001
      - 4008
    remoteAccess: false
    localDeps: "
      mix deps.get --only prod
      mix compile
      brunch build --production
      mix phx.digest
      mix ecto.migrate
      mix phx.server
    "
    env:
      DB_DRIVER: "pgsql"
      DB_HOST: "{{=service('db').getMasterAlias()}}"
      DB_DATABASE: "{{=service('db').getEnv('POSTGRES_USER')}}"
      DB_USERNAME: "{{=service('db').getEnv('POSTGRES_USER')}}"
      DB_PASSWORD: "{{=service('db').getEnv('POSTGRES_PASSWORD')}}"
      APP_KEY: "{{=randomString(32)}}"
      MIX_ENV: "prod"
    deployTo:
      - platform

  - name: web
    type: nginx
    version: 1.13
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: platform
    deployTo:
      - platform

hosts:
  - name: platform
    requirements:
      cores: 1
      memory: 1

  - name: gandalf
    requirements:
      cores: 1
      memory: 1
